version: '3'
services:
  metabase:
    depends_on:
      - postgres
    container_name: metabase_service
    image: metabase/metabase
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/metabase/metabase-data:/metabase-data
  postgres:
    container_name: postgres_service
    image: postgres:alpine
    shm_size: '2gb'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
