version: '3'
services:
  metabase:
    image: metabase/metabase
    environment: 
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/metabase/metabase-data:/metabase-data
  postgres:
    image: postgres:alpine
    shm_size: '2gb'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
